[package]
name = "synixe-db"
version = "0.1.0"
edition = "2021"

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats", "sqlx"] }
synixe-events = { path = "../../lib/events" }
synixe-meta = { path = "../../lib/meta" }
synixe-model = { path = "../../lib/model", features = ["sqlx", "gear", "mission-schedule", "garage"] }
anyhow = { workspace = true }
async-trait = { workspace = true }
nats = { workspace = true }
reqwest = { version = "0.11.13", features = ["json"] }
serenity = { workspace = true, features = [ "builder" ] }
serde_json = "1"
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-native-tls", "offline", "time", "uuid", "json"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[build-dependencies]
vergen = { workspace = true, features = ["git"]}
