[package]
name = "synixe-schedule"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
tokio-simple-scheduler = "0.1.1"
reqwest = { version = "0.11.12" }
scraper = "0.13.0"
serenity = { workspace = true, features = ["builder"] }
