apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "synixe.fullname" . }}-scheduler
  labels:
    {{- include "synixe.labels" . | nindent 4 }}
    app: scheduler
spec:
  replicas: 0 # TODO enable
  selector:
    matchLabels:
      {{- include "synixe.selectorLabels" . | nindent 6 }}
      app: scheduler
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "synixe.selectorLabels" . | nindent 8 }}
        app: scheduler
    spec:
      imagePullSecrets:
        {{- if .Values.regcred }}
        - name: regcred
        {{- end }}
        {{- with .Values.imagePullSecrets }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "synixe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: synixe-scheduler
          env:
            - name: NATS_URL
              value: {{ .Values.config.nats_url | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "ghcr.io/dynulo/synixe-scheduler:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ dig "resources" "requests" "scheduler" "memory" "5Mi" (.Values | merge (dict)) | quote }}
              cpu: {{ dig "resources" "requests" "scheduler" "cpu" "100m" (.Values | merge (dict)) | quote }}
            limits:
              memory: {{ dig "resources" "limits" "scheduler" "memory" "20Mi" (.Values | merge (dict)) | quote }}
              cpu: {{ dig "resources" "limits" "scheduler" "cpu" "500m" (.Values | merge (dict)) | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
