apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    {{- include "synixe.labels" . | nindent 4 }}
  name: {{ include "synixe.fullname" . }}-hooks
spec:
  entryPoints:
  - websecure
  routes:
  - match: PathPrefix(`/hooks`)
    services:
    - name: {{ include "synixe.fullname" . }}-hooks
      port: http
