-- Add migration script here
CREATE TABLE IF NOT EXISTS members_steam (
    member VARCHAR(128) PRIMARY KEY,
    steam VARCHAR(128) NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS members_dlc (
    member VARCHAR(128) PRIMARY KEY,
    dlc INTEGER ARRAY NOT NULL,
    created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
