[package]
name = "synixe-ai"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats"] }
synixe-events = { path = "../../lib/events" }
synixe-proc = { path = "../../lib/proc" }

nats = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
