apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  labels:
    {{- include "synixe.labels" . | nindent 4 }}
  name: {{ include "synixe.fullname" . }}-nats
spec:
  entryPoints:
  - nats
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - name: synixe-nats
      port: client
