apiVersion: v1
kind: Service
metadata:
  name: {{ include "synixe.fullname" . }}-calendar
  labels:
    app: calendar
    {{- include "synixe.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: calendar
    {{- include "synixe.selectorLabels" . | nindent 4 }}
