apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    {{- include "synixe.labels" . | nindent 4 }}
  name: {{ include "synixe.fullname" . }}-api
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`cluster.synixe.contractors`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: {{ include "synixe.fullname" . }}-api
      port: http
  tls:
    secretName: cluster-synixe-cert
