PREP(loadout_ext);
PREP(shop_ext);

PREP(loadout_clean);
PREP(loadout_items);
PREP(loadout_onChange);

PREP(shop_arsenal_btnHide);
PREP(shop_arsenal_closed);
PREP(shop_arsenal_leftPanelFilled);
// PREP(shop_arsenal_loadoutListFilled);
PREP(shop_arsenal_opened);
PREP(shop_arsenal_rightPanelFilled);
PREP(shop_arsenal_rightPanelSelChanged);
PREP(shop_arsenal_sort_owned);
PREP(shop_arsenal_sort_price);
PREP(shop_checkout_onLoad);
PREP(shop_enter);
PREP(shop_init);
PREP(shop_item_listing);
PREP(shop_item_owned);
PREP(shop_item_price);
PREP(shop_item_roles);
PREP(shop_items_allowed);
PREP(shop_items_cost);
PREP(shop_items_difference);
PREP(shop_items_purchasable);
PREP(shop_items_purchase);
PREP(shop_items_removeOwned);
PREP(shop_lockBackpack);
PREP(shop_open);
PREP(shop_pfh_balance);
