[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats"] }
synixe-events = { path = "../../lib/events" }
synixe-proc = { path = "../../lib/proc" }
synixe-poll-runner = { path = "../../utils/poll-runner" }

axum = { workspace = true }
base64 = "0.22.0"
nats = { workspace = true }
rsa = { workspace = true }
serenity = { workspace = true, features = ["builder"] }
tera = "1.19.1"
tokio = { workspace = true, features = ["full"] }
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
tracing = { workspace = true }
uuid = "1.8.0"
