[package]
name = "synixe-scheduler"
version = "0.1.0"
edition = "2021"

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats", "otlp"] }
synixe-events = { path = "../../lib/events" }
synixe-meta = { path = "../../lib/meta" }
synixe-proc = { path = "../../lib/proc" }

log = { workspace = true }
nats = { workspace = true }
opentelemetry = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-simple-scheduler = "0.1.2"

[build-dependencies]
vergen = { workspace = true, features = ["git"] }
