[package]
name = "synixe-scheduler"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats"] }
synixe-events = { path = "../../lib/events" }
synixe-meta = { path = "../../lib/meta" }
synixe-proc = { path = "../../lib/proc" }

nats = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-simple-scheduler = "0.1.2"
tracing = { workspace = true }
