[package]
name = "synixe-bot"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats"] }
synixe-events = { path = "../../lib/events" }
synixe-meta = { path = "../../lib/meta" }
synixe-proc = { path = "../../lib/proc" }
synixe-model = { path = "../../lib/model", features = ["missions"] }

anyhow = { workspace = true }
async-openai = "0.19.0"
async-trait = { workspace = true }
git2 = "0.20.2"
nats = { workspace = true }
rand = "0.9.2"
regex = "1.11.3"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serenity = { workspace = true, features = ["builder", "cache", "client", "collector", "gateway", "http", "model", "utils", "rustls_backend"] }
strum = { workspace = true }
time = { workspace = true }
time-tz = "2.0.0"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
uuid = { workspace = true }
