[package]
name = "synixe-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats", "otlp"] }
synixe-events = { path = "../../lib/events" }
synixe-meta = { path = "../../lib/meta" }
synixe-proc = { path = "../../lib/proc" }

anyhow = "1.0.66"
async-trait = { workspace = true }
log = { workspace = true }
nats = { workspace = true }
opentelemetry = { workspace = true }
reqwest = { version = "0.11.13", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.88"
serenity = { workspace = true, features = ["builder", "cache", "client", "collector", "gateway", "http", "model", "utils", "rustls_backend"]}
time = { workspace = true }
time-tz = "1.0.2"
tokio = { version = "1.22.0", features = ["full"] }
uuid = { workspace = true }

[build-dependencies]
vergen = { workspace = true }
