[package]
name = "synixe-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats"] }
synixe-events = { path = "../../lib/events" }
synixe-meta = { path = "../../lib/meta" }
synixe-proc = { path = "../../lib/proc" }
synixe-model = { path = "../../lib/model", features = ["missions"] }

anyhow = { workspace = true }
async-trait = { workspace = true }
nats = { workspace = true }
reqwest = { version = "0.11.13", features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.91"
serenity = { workspace = true, features = ["builder", "cache", "client", "collector", "gateway", "http", "model", "utils", "rustls_backend"] }
time = { workspace = true }
time-tz = "1.0.2"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
vergen = { workspace = true }
