[package]
name = "synixe-calendar"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bootstrap = { path = "../../lib/bootstrap", features = ["nats"] }
synixe-events = { path = "../../lib/events" }
synixe-proc = { path = "../../lib/proc" }
synixe-model = { path = "../../lib/model", features = ["missions"] }

axum = { workspace = true }
chrono = "0.4.35"
icalendar = "0.16.0"
nats = { workspace = true }
time = { workspace = true }
time-tz = "2.0.0"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
