name: docker

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/docker.yaml
      - Cargo.toml
      - bin/docker/**
      - lib/bootstrap/**
      - lib/events/**
      - lib/proc/**

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v1
        with:
          key: docker

      - run: cargo build --release
        working-directory: ./bin/docker

      - run: cp target/release/synixe-docker ./bin/docker/synixe-docker

      - name: Build Image
        working-directory: ./bin/docker
        run: docker build . -t docker

      - name: Tag Image
        run: docker tag docker ghcr.io/synixecontractors/apps-docker:latest

      - name: Push Image
        run: docker push ghcr.io/synixecontractors/apps-docker:latest
