name: executor

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/executor.yaml
      - Cargo.toml
      - bin/executor/**
      - lib/bootstrap/**
      - lib/events/**
      - lib/meta/**
      - lib/proc/**

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: Swatinem/rust-cache@v1

      - run: cargo build --release
        working-directory: ./bin/executor

      - run: cp target/release/synixe-executor ./bin/executor/synixe-executor

      - name: Build Image
        working-directory: ./bin/executor
        run: docker build . -t executor

      - name: Tag Image
        run: docker tag executor ghcr.io/synixecontractors/apps-executor:latest

      - name: Push Image
        run: docker push ghcr.io/synixecontractors/apps-executor:latest
