# name: coverage

# on: [push]

# jobs:
#   coverage:
#     runs-on: ubuntu-latest
#     container:
#       image: xd009642/tarpaulin
#       options: --security-opt seccomp=unconfined
#     steps:
#       - uses: actions/checkout@v2

#       - uses: Swatinem/rust-cache@v1
#         with:
#           key: coverage

#       - uses: actions-rs/toolchain@v1
#         with:
#           profile: minimal
#           toolchain: stable
#           override: true

#       - name: Generate code coverage
#         run: |
#           cargo tarpaulin --verbose --all-features --workspace --timeout 240 --out Xml

#       - name: Upload to codecov.io
#         uses: codecov/codecov-action@v1
#         with:
#           fail_ci_if_error:     true
